### PR TITLE
Update settings.json

### PR DESCRIPTION
**Pull request by gbowne1**
Update this settings.json for those who do not have configured Visual Studio Code installations  This should be considered a draft global settings.json for the User space in Visual Studio Code (VSCode) and is not tested.  From there the user could theoretically could set up their preferences.  

This commit includes default Language specific settings.

I would like to see this evolve into a decent global settings.json file for use in User settings in Visual Studio Code.. other than font and theme settings.

### CODE REVIEW

**Comment by gbowne1** [comment]
@taotnpwaft/members

**Comment by gbowne1** [comment]
I don't know if this file should include the original configuration setting from the first commit:

 `"livePreview.defaultPreviewPath": "/website/newpassword.html"`

**Review by hitblast — APPROVED** [review]
Looks good to me.

**Comment by gbowne1** [comment]
@hitblast 

the Python settings need to be fixed.  but other than that I think this would be a good start for anyone using VSCode that does not have it set up yet.

Am open to ideas.

**Comment by gbowne1** [comment]
@hitblast @BenCos17 

Theres still some issues with this settings.json file but should be fine.  I will merge if there is at least one more review from someone other than me.

The main problem with the new changes to settings.json is the Python language specific settings.

Again this relies heavily on the user having common extensions installed like ESLint and Prettier.

I also am looking for C, C# and C++ language specific settings.  I especially am having problems with VS Code saying that .c & .h files are a different language in the language mode thing in the bottom status bar.  I have to manually choose C language every time.

In the output section of the terminal pane it also tries to run Pip settings at startup.

**Review by gbowne1 — COMMENTED** [review]
The original settings.json here was pretty much empty.

This adds especially common languge specific settings used in WebDev, etc.

This needs to be both improved as well as tested. 

This settings file would be useful for those users of VSCode that have default settings or have not configured their VSCode yet.  Especially if you use this entire folder/dir.

**Review by gbowne1 — COMMENTED** [review]
I tried with this PR to make the best possible settings.json at least as a starter.

I have more edits coming.

**Comment by gbowne1** [comment]
This needs some more work that I will add in the next PR.

**Pull request merged**
